baseURL = "https://hopton10k.run/"
languageCode = "en-gb"
title = "Hopton 10k road and trail running race, Mirfield, West Yorkshire"
theme = "universal"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-143111091-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Route"
    url  = "/#route"
    weight = 2

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 2

[[menu.main]]
    name = "Enter Now"
    url  = "https://racebest.com/races/k32qh"
    weight = 3

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 4

[[menu.main]]
    name = "Sponsorship"
    identifier = "sponsor"
    url  = "/sponsorship/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/hopton10k"
    pre = "<i class='fab fa-2x fa-facebook-f'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/hopton10k"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@hopton10k.run"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Rob MacDonald"
    defaultKeywords = ["hopton10k", "10k", "hopton", "race", "running", "trail"]
    defaultDescription = "Hopton 10k. A ten kilometre running race over mixed terrain, based in Lower Hopton, Mirfield, West Yorkshire."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyB37dKVIzGNxWhhJHo_NfoBTLALR3b8SY0"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "hopton"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@hopton10k.run"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2019, Hopton 10k."

    # Format dates with Go's time formatting
    date_format = "2 Jan 06"

    logo = "/images/logos/hoptonlogotext.png"
    logo_small = "/images/logos/hoptonlogotext.png"
    # address = """<p><strong>Hopton 10k</strong>
    #     <br>12 New Tanhouse
    #     <br>Mirfield
    #     <br>WF14 9BP
    #     <br>West Yorkshire
    #     <br>
    #     <strong>Great Britain</strong>
    #   </p>
    #   """
    latitude = "53.672209"
    longitude = "-1.699673"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We havesaid about us."

[params.see_more]
    enable = true
    icon = "fas fa-running"
    title = "Enter Now"
    subtitle = "Tickets are selling fast, reserve your place now to avoid disappointment."
    link_url = "https://racebest.com/races/k32qh"
    link_text = "Register now"

[params.long_desc]
    enable = true
    icon = "fas fa-question"
    title = "Why have we created the Hopton 10k?"
    subtitle = "The woods and fields around Hopton are a great place to run offering some great variety. There are steep climbs, woodland glades, bridleways, and great views over the calder valley. We thought it would make a great place to hold an annual race. So grab your mucky trainers and get involved!"
    # link_url = "https://racebest.com/races/k32qh"
    # link_text = "Enter the race"

[params.sponsors]
    enable = true
    title = "Our sponsors"
    subtitle = ""

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our clients"
    subtitle = ""

[params.routemap]
    enable = true
    routeid = "17818988"

[params.recent_posts]
    enable = true
    title = "Latest News"
    subtitle = ""
